#!/bin/bash

DISTRO="${1:-$(lsb_release -c -s)}"
CHROOT="${2:-$DISTRO-chroot}"

KEYSERVER="hkp://keyserver.ubuntu.com"
POP_OS_KEYS="204DD8AEC33A7AFF 1E5F8BBC5BEB10AE"

## Functions

log()
{
    echo "$(basename $0): $*"
}


build_chroot()
{
    if [ ! -e $CHROOT ]; then
        debootstrap $DISTRO $CHROOT
    else
        log "$CHROOT exists, skipping"
    fi
}


in_chroot()
{
    chroot $CHROOT $*
}


mount_filesystems()
{
    mountpoint -q $CHROOT/proc || mount -t proc none $CHROOT/proc
    mountpoint -q $CHROOT/dev  || mount -o bind /dev $CHROOT/dev

    # We sleep briefly to avoid 'target is busy' message for /proc
    trap "sleep 0.5; umount $CHROOT/{dev,proc}" EXIT
}


install_pop_os_keys()
{
    export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE="DontWarn"

    local key
    for key in $POP_OS_KEYS; do
        if ! grep -qs 'PGP PUBLIC KEY' <(in_chroot apt-key export "$key"); then
            in_chroot apt-key adv --keyserver "$KEYSERVER" --recv-keys "$key"
        else
            log "$key already installed, skipping"
        fi
    done
}


add_apt_sources()
{
    # We'll need gpg to retrieve the APT keys for the Pop!_OS sources
    apt-get update
    in_chroot apt-get update
    in_chroot apt-get install -y gpg

    local files=(
        /etc/apt/sources.list
        /etc/apt/sources.list.d/system76-ubuntu-pop-$DISTRO.list
    )
    for file in "${files[@]}"; do
        cp $file "$CHROOT/$(dirname $file)/"
    done

    install_pop_os_keys
}


update_packages()
{
    in_chroot apt-get update
    in_chroot apt-get upgrade -y
}


install_build_dependencies()
{
    local script="$CHROOT/root/install-build-deps.sh"

    cat > $script <<EOF
#!/bin/sh

# If LANG and LC_ALL aren't set tex-common won't install cleanly
export LANG="C.UTF-8" LC_ALL="C.UTF-8"

apt-get build-dep -y linux "linux-image-$(uname -r)"
EOF

    chmod +x $script
    in_chroot "${script#$CHROOT}"
}


build_kernel()
{
    local script="$CHROOT/root/build-kernel.sh"
    cat > $script <<EOF
#!/bin/sh

cd /usr/src

VERSION="$(uname -r)"

apt-get source "linux-image-$VERSION"

cd linux-${VERSION%%-*}
fakeroot debian/rules clean
fakeroot debian/rules binary-headers binary-generic binary-indep
EOF
    
    chmod +x $script
    in_chroot "${script#$CHROOT}"
}


## Main program

set -e

[ -n "$DEBUG" ] && set -x

build_chroot
mount_filesystems
add_apt_sources
update_packages
install_build_dependencies
# build_kernel
