#!/bin/sh

DISTRO="${1:-$(lsb_release -c -s)}"
CHROOT="${2:-$DISTRO-chroot}"

KEYSERVER="hkp://keyserver.ubuntu.com"
POP_OS_KEY="204DD8AEC33A7AFF"

## Functions

log()
{
    echo "$(basename $0): $*"
}


build_chroot()
{
    if [ ! -e $CHROOT ]; then
        debootstrap $DISTRO $CHROOT
    else
        log "$CHROOT exists, skipping"
    fi
}


configure_apt()
{
    cp /etc/apt/sources.list $CHROOT/etc/apt/
}


in_chroot()
{
    chroot $CHROOT $*
}


install_pop_os_key()
{
    export APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE="DontWarn"
    if [ "$(apt-key export $POP_OS_KEY)" = "" ]; then
        in_chroot apt-get install -y gpg
        in_chroot apt-key adv --keyserver "$KEYSERVER" --recv-keys "$POP_OS_KEY"
    else
        log "$POP_OS_KEY already installed, skipping"
    fi
}


update_packages()
{
    in_chroot apt-get update
    in_chroot apt-get upgrade -y
}


## Main program

set -e

build_chroot
configure_apt
install_pop_os_key
update_packages
